from app.schemas.video import (
    VideoBase,
    VideoCreate,
    VideoUpdate,
    VideoResponse,
    VideoListResponse,
    VideoBrief,
    VideoDetailResponse,
)
from app.schemas.subtitle import (
    SubtitleBase,
    SubtitleCreate,
    SubtitleResponse,
    SubtitleListResponse,
)
from app.schemas.tag import (
    TagBase,
    TagCreate,
    TagUpdate,
    TagResponse,
    TagListResponse,
)
from app.schemas.word_card import (
    WordCardBase,
    WordCardCreate,
    WordCardResponse,
    WordCardListResponse,
)
from app.schemas.phrase_card import (
    PhraseCardBase,
    PhraseCardCreate,
    PhraseCardResponse,
    PhraseCardListResponse,
)
from app.schemas.user import (
    UserRead,
    UserCreate,
    UserUpdate,
)
from app.schemas.auth import (
    SmsSendRequest,
    SmsVerifyRequest,
    ActivationVerifyRequest,
    ActivationVerifyResponse,
    ActivationRegisterRequest,
    ActivationGenerateRequest,
    ActivationGenerateResponse,
    TokenResponse,
)
from app.schemas.learning import (
    LearningProgressUpdateRequest,
    LearningProgressResponse,
    LearningRecentItem,
    LearningRecentResponse,
    LearningCompletedItem,
    LearningCompletedResponse,
    FavoriteItem,
    FavoriteListResponse,
    FavoriteActionResponse,
    FavoriteCheckResponse,
    FavoriteBatchCheckRequest,
    FavoriteBatchCheckResponse,
    SubtitleFavoriteItem,
    SubtitleFavoriteListResponse,
    SubtitleFavoriteActionResponse,
    SubtitleFavoriteCheckResponse,
    WordFavoriteItem,
    WordFavoriteListResponse,
    WordFavoriteActionResponse,
    WordFavoriteCheckResponse,
    PhraseFavoriteItem,
    PhraseFavoriteListResponse,
    PhraseFavoriteActionResponse,
    PhraseFavoriteCheckResponse,
)

__all__ = [
    # Video
    "VideoBase",
    "VideoCreate",
    "VideoUpdate",
    "VideoResponse",
    "VideoListResponse",
    "VideoBrief",
    "VideoDetailResponse",
    # Subtitle
    "SubtitleBase",
    "SubtitleCreate",
    "SubtitleResponse",
    "SubtitleListResponse",
    # Tag
    "TagBase",
    "TagCreate",
    "TagUpdate",
    "TagResponse",
    "TagListResponse",
    # Word Card
    "WordCardBase",
    "WordCardCreate",
    "WordCardResponse",
    "WordCardListResponse",
    # Phrase Card
    "PhraseCardBase",
    "PhraseCardCreate",
    "PhraseCardResponse",
    "PhraseCardListResponse",
    # User
    "UserRead",
    "UserCreate",
    "UserUpdate",
    # Auth
    "SmsSendRequest",
    "SmsVerifyRequest",
    "ActivationVerifyRequest",
    "ActivationVerifyResponse",
    "ActivationRegisterRequest",
    "ActivationGenerateRequest",
    "ActivationGenerateResponse",
    "TokenResponse",
    # Learning & Favorites
    "LearningProgressUpdateRequest",
    "LearningProgressResponse",
    "LearningRecentItem",
    "LearningRecentResponse",
    "LearningCompletedItem",
    "LearningCompletedResponse",
    "FavoriteItem",
    "FavoriteListResponse",
    "FavoriteActionResponse",
    "FavoriteCheckResponse",
    "FavoriteBatchCheckRequest",
    "FavoriteBatchCheckResponse",
    "SubtitleFavoriteItem",
    "SubtitleFavoriteListResponse",
    "SubtitleFavoriteActionResponse",
    "SubtitleFavoriteCheckResponse",
    "WordFavoriteItem",
    "WordFavoriteListResponse",
    "WordFavoriteActionResponse",
    "WordFavoriteCheckResponse",
    "PhraseFavoriteItem",
    "PhraseFavoriteListResponse",
    "PhraseFavoriteActionResponse",
    "PhraseFavoriteCheckResponse",
]
