"""add word_refs to subtitles

Revision ID: 13956fe485c2
Revises: 1d0cc68f3fbf
Create Date: 2025-12-22 01:06:36.903182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13956fe485c2'
down_revision: Union[str, None] = '1d0cc68f3fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtitles', sa.Column('word_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtitles', 'word_refs')
    # ### end Alembic commands ###
