"""make video_url nullable

Revision ID: 1d0cc68f3fbf
Revises: 9524221ea631
Create Date: 2025-12-22 00:42:52.344885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0cc68f3fbf'
down_revision: Union[str, None] = '9524221ea631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'video_url',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('videos', 'video_url',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
