"""add title_zh and description_zh to videos

Revision ID: 3af549d9e535
Revises: add_video_segments
Create Date: 2025-12-23 18:08:52.918905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af549d9e535'
down_revision: Union[str, None] = 'add_video_segments'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('title_zh', sa.String(length=255), nullable=True))
    op.add_column('videos', sa.Column('description_zh', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_videos_video_type'), table_name='videos')
    op.drop_constraint(op.f('fk_videos_parent_id'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'videos', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('fk_videos_parent_id'), 'videos', 'videos', ['parent_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_videos_video_type'), 'videos', ['video_type'], unique=False)
    op.drop_column('videos', 'description_zh')
    op.drop_column('videos', 'title_zh')
    # ### end Alembic commands ###
