"""初始化数据库

Revision ID: 9524221ea631
Revises: 
Create Date: 2025-12-18 17:49:46.116629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9524221ea631'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('youtube_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('original_author', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_display_order'), 'videos', ['display_order'], unique=False)
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_index(op.f('ix_videos_youtube_id'), 'videos', ['youtube_id'], unique=True)
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('end_time', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('english_text', sa.Text(), nullable=False),
    sa.Column('chinese_text', sa.Text(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_video_id'), 'subtitles', ['video_id'], unique=False)
    op.create_table('video_tags',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'tag_id')
    )
    op.create_table('phrase_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('phrase', sa.String(length=200), nullable=False),
    sa.Column('phonetic', sa.String(length=200), nullable=True),
    sa.Column('chinese_definition', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('context_translation', sa.Text(), nullable=True),
    sa.Column('subtitle_id', sa.Integer(), nullable=True),
    sa.Column('first_appearance_time', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_cards_phrase'), 'phrase_cards', ['phrase'], unique=False)
    op.create_index(op.f('ix_phrase_cards_video_id'), 'phrase_cards', ['video_id'], unique=False)
    op.create_table('word_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('chinese_definition', sa.Text(), nullable=True),
    sa.Column('english_definition', sa.Text(), nullable=True),
    sa.Column('example_from_video', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('subtitle_id', sa.Integer(), nullable=True),
    sa.Column('first_appearance_time', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=20), nullable=True),
    sa.Column('other_pos_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_cards_video_id'), 'word_cards', ['video_id'], unique=False)
    op.create_index(op.f('ix_word_cards_word'), 'word_cards', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_cards_word'), table_name='word_cards')
    op.drop_index(op.f('ix_word_cards_video_id'), table_name='word_cards')
    op.drop_table('word_cards')
    op.drop_index(op.f('ix_phrase_cards_video_id'), table_name='phrase_cards')
    op.drop_index(op.f('ix_phrase_cards_phrase'), table_name='phrase_cards')
    op.drop_table('phrase_cards')
    op.drop_table('video_tags')
    op.drop_index(op.f('ix_subtitles_video_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_videos_youtube_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_index(op.f('ix_videos_display_order'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
