"""Initial database schema

Revision ID: e6266d9d40a9
Revises: 
Create Date: 2026-01-27 00:29:21.439254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import fastapi_users_db_sqlalchemy

# revision identifiers, used by Alembic.
revision: str = 'e6266d9d40a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_codes_phone'), 'sms_codes', ['phone'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('users',
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('apple_sub', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_apple_sub'), 'users', ['apple_sub'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('title_zh', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_zh', sa.Text(), nullable=True),
    sa.Column('video_url', sa.Text(), nullable=True),
    sa.Column('vod_file_id', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('segment_index', sa.Integer(), nullable=True),
    sa.Column('video_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('is_free', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('youtube_id', sa.String(length=50), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('original_author', sa.String(length=255), nullable=True),
    sa.Column('author_avatar_url', sa.Text(), nullable=True),
    sa.Column('categories', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categories_zh', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_display_order'), 'videos', ['display_order'], unique=False)
    op.create_index(op.f('ix_videos_parent_id'), 'videos', ['parent_id'], unique=False)
    op.create_index(op.f('ix_videos_title'), 'videos', ['title'], unique=False)
    op.create_index(op.f('ix_videos_youtube_id'), 'videos', ['youtube_id'], unique=True)
    op.create_table('subtitles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('start_time', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('end_time', sa.DECIMAL(precision=10, scale=3), nullable=False),
    sa.Column('english_text', sa.Text(), nullable=False),
    sa.Column('chinese_text', sa.Text(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('word_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtitles_video_id'), 'subtitles', ['video_id'], unique=False)
    op.create_table('user_video_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('favorited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_favorites_user_video')
    )
    op.create_index('ix_user_video_favorites_user_favorited_at', 'user_video_favorites', ['user_id', 'favorited_at'], unique=False)
    op.create_index(op.f('ix_user_video_favorites_user_id'), 'user_video_favorites', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_video_favorites_video_id'), 'user_video_favorites', ['video_id'], unique=False)
    op.create_table('user_video_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('current_progress', sa.Integer(), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('last_watched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'video_id', name='uq_user_video_progress_user_video')
    )
    op.create_index('ix_user_video_progress_user_completed', 'user_video_progress', ['user_id', 'is_completed', 'completed_at'], unique=False)
    op.create_index(op.f('ix_user_video_progress_user_id'), 'user_video_progress', ['user_id'], unique=False)
    op.create_index('ix_user_video_progress_user_lastwatched', 'user_video_progress', ['user_id', 'last_watched_at'], unique=False)
    op.create_index(op.f('ix_user_video_progress_video_id'), 'user_video_progress', ['video_id'], unique=False)
    op.create_table('video_tags',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('video_id', 'tag_id')
    )
    op.create_table('phrase_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('phrase', sa.String(length=200), nullable=False),
    sa.Column('phonetic', sa.String(length=200), nullable=True),
    sa.Column('chinese_definition', sa.Text(), nullable=True),
    sa.Column('synonyms', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('context_translation', sa.Text(), nullable=True),
    sa.Column('subtitle_id', sa.Integer(), nullable=True),
    sa.Column('first_appearance_time', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_cards_phrase'), 'phrase_cards', ['phrase'], unique=False)
    op.create_index(op.f('ix_phrase_cards_video_id'), 'phrase_cards', ['video_id'], unique=False)
    op.create_table('word_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('phonetic', sa.String(length=100), nullable=True),
    sa.Column('chinese_definition', sa.Text(), nullable=True),
    sa.Column('english_definition', sa.Text(), nullable=True),
    sa.Column('example_from_video', sa.Text(), nullable=True),
    sa.Column('example_translation', sa.Text(), nullable=True),
    sa.Column('subtitle_id', sa.Integer(), nullable=True),
    sa.Column('first_appearance_time', sa.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('difficulty_level', sa.Integer(), nullable=True),
    sa.Column('frequency_rank', sa.Integer(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=20), nullable=True),
    sa.Column('other_pos_definitions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subtitle_id'], ['subtitles.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_cards_video_id'), 'word_cards', ['video_id'], unique=False)
    op.create_index(op.f('ix_word_cards_word'), 'word_cards', ['word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_cards_word'), table_name='word_cards')
    op.drop_index(op.f('ix_word_cards_video_id'), table_name='word_cards')
    op.drop_table('word_cards')
    op.drop_index(op.f('ix_phrase_cards_video_id'), table_name='phrase_cards')
    op.drop_index(op.f('ix_phrase_cards_phrase'), table_name='phrase_cards')
    op.drop_table('phrase_cards')
    op.drop_table('video_tags')
    op.drop_index(op.f('ix_user_video_progress_video_id'), table_name='user_video_progress')
    op.drop_index('ix_user_video_progress_user_lastwatched', table_name='user_video_progress')
    op.drop_index(op.f('ix_user_video_progress_user_id'), table_name='user_video_progress')
    op.drop_index('ix_user_video_progress_user_completed', table_name='user_video_progress')
    op.drop_table('user_video_progress')
    op.drop_index(op.f('ix_user_video_favorites_video_id'), table_name='user_video_favorites')
    op.drop_index(op.f('ix_user_video_favorites_user_id'), table_name='user_video_favorites')
    op.drop_index('ix_user_video_favorites_user_favorited_at', table_name='user_video_favorites')
    op.drop_table('user_video_favorites')
    op.drop_index(op.f('ix_subtitles_video_id'), table_name='subtitles')
    op.drop_table('subtitles')
    op.drop_index(op.f('ix_videos_youtube_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_title'), table_name='videos')
    op.drop_index(op.f('ix_videos_parent_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_display_order'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_apple_sub'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_sms_codes_phone'), table_name='sms_codes')
    op.drop_table('sms_codes')
    # ### end Alembic commands ###
